export const DESCRIPTIONS = [
'red es un sistema interconectado que permite la transmisión de datos y comunicación a distancia en telecomunicaciones. Incluye internet, telefonía móvil y redes de televisión por cable.',
'es un punto de conexión en una red para intercambio de información. Puede ser servidor, computadora, router, dispositivo móvil, etc.',
'dispositivo que concentra y transmite datos en una red LAN. Conecta varios dispositivos a la red, reenvia por sus bocas lo que entro por una.',
'enruta paquetes de datos entre redes y permite conectar varios dispositivos a una red. Realiza tareas como filtrado de paquetes, direccionamiento IP entre otras',
'conecta varios dispositivos en una red y controla la transmisión de datos. Mejora eficiencia de la red y se usa en redes LAN para conectar computadoras, dispositivos de red y otros dispositivos electrónicos.',
'medio físico para transmitir datos y energía eléctrica. Se usa en telecomunicaciones para conectar dispositivos de red y transmitir señales de voz, datos y video.',
'es un equipo de hardware o software que proporciona servicios a otros dispositivos en una red. Puede almacenar, procesar y transmitir datos, aplicaciones y recursos compartidos a otros dispositivos en la red',
'es un dispositivo o software que solicita y utiliza servicios o recursos proporcionados por un servidor en una red. Puede ser una computadora, un dispositivo móvil, una aplicación de software, entre otros.',
'es un proceso para proteger la información transformándola en una forma ilegible. Se usa para proteger información confidencial durante transmisión o almacenamiento y existen diferentes tipos de cifrado para lograr seguridad adicional',
'es una unidad básica de información. Puede ser un número, una palabra, una imagen, un sonido, entre otros. ',
'es una unidad de información enviada en una red, compuesta de información de cabecera y carga útil. La cabecera incluye detalles de origen y destino, mientras que la carga útil contiene la información real. Los paquetes se transmiten y ensamblan en su destino para reconstruir la información original.',
'área temporal de almacenamiento en un sistema informático, utilizada para almacenar datos temporalmente mientras se procesan o se transmiten.',
'Una unidad de medida de información compuesta de 8 bits.',
'unidad más básica de información en informática, que puede tener un valor de 0 o 1.',
'instrucciones escritas en un lenguaje de programación que pueden ser ejecutadas por un computadora para realizar tareas específicas.',
'un dispositivo que transmite o recibe señales electromagnéticas a través del aire o del espacio.',
'un dispositivo que permite la transmisión de audio a través de una línea telefónica.',
'un dispositivo o software que permite seleccionar o eliminar ciertos elementos de una señal o información, dejando pasar solo aquellos que cumplen ciertos criterios.',
'la unidad central de procesamiento de una sistema informatico, responsable de realizar cálculos y ejecutar instrucciones.',
'es un tipo de memoria de acceso aleatorio utilizada por los sistemas informaticos para almacenar y acceder a datos y programas de manera más rápida.',
'conjunto de componentes integrados en una placa de circuito que controlan la comunicación entre los componentes de un sistema.',
'un estándar para conectar componentes en una sistema informatico, como tarjetas de sonido, tarjetas gráficas, y adaptadores de red.',
'se refiere a algo que existe en un entorno virtual, es decir, que está generado por software y no es un objeto real',
'un dispositivo que mide o detecta ciertos valores, como la temperatura, la luz, el sonido, entre otros, y los convierte en una señal eléctrica o digital para su procesamiento y análisis.',
'es una herramienta gratuita y de código abierto que permite crear unidades USB booteables a partir de imágenes de ISO de sistemas operativos y también puede utilizarse para formatear unidades USB',
'Una ISO es un archivo que contiene una imagen exacta de un CD o DVD, incluyendo todos los archivos y carpetas en su estructura original. Esta imagen se utiliza comúnmente para distribuir sistemas operativos y software',
]