version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
          - conf:/etc/nginx/conf.d
          - vhost:/etc/nginx/vhost.d
          - dhparam:/etc/nginx/dhparam
          - certs:/etc/nginx/certs:ro
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /usr/share/nginx/html



    letsencrypt-proxy:
      image: nginxproxy/acme-companion
      container_name: letsencrypt-proxy
      volumes_from:
        - nginx-proxy
      volumes:
        - certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        - DEFAULT_EMAIL=mikeldiezgarcia@gmail.com
        - NGINX_PROXY_CONTAINER=nginx-proxy
      depends_on:
        - "nginx-proxy"


    wordle1:
      build:
        context: ../
        dockerfile: docker/Dockerfile
      image: teleco_prod:v0.1
      expose:
          - 3000
      container_name: wordle_teleco
      environment:
        - VIRTUAL_HOST=wordle.arraiz.me
        - LETSENCRYPT_HOST=wordle.arraiz.me
        - HTTPS_METHOD=redirect
      depends_on:
        - "nginx-proxy"
        - "letsencrypt-proxy" 

volumes:
  conf:
  vhost:
  dhparam:
  certs: