version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - letsencrypt-certs:/etc/nginx/certs
          - letsencrypt-vhost-d:/etc/nginx/vhost.d
          - letsencrypt-html:/usr/share/nginx/html


    letsencrypt-proxy:
      image: jrcs/letsencrypt-nginx-proxy-companion
      container_name: letsencrypt-proxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - letsencrypt-certs:/etc/nginx/certs
        - letsencrypt-vhost-d:/etc/nginx/vhost.d
      environment:
        - DEFAULT_EMAIL=mikeldiezgarcia@gmail.com
        - NGINX_PROXY_CONTAINER=nginx-proxy


    wordle1:
      build:
        context: ../
        dockerfile: docker/Dockerfile
      image: teleco_prod:v0.1
      expose:
          - 3000
      container_name: wordle_teleco
      environment:
        - VIRTUAL_HOST=wordle.arraiz.me
        - LETSENCRYPT_HOST=wordle.arraiz.me
        - HTTPS_METHOD=redirect

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html: